/*
** EPITECH PROJECT, 2018
** strace
** File description:
** all syscall
*/

#ifndef ALL_MY_SYSCALLS_H_
# define ALL_MY_SYSCALLS_H_

enum d_type {
    OFF = 0,
    INT , CHAR , CHAR_PTR , CHAR_PTRPTR ,
    U   , U_L  , LONG     , PTR         ,
    STRUCT,
    RETVAL = LONG,
};

typedef struct
{
    char *name;
    enum d_type as[6];
    enum d_type ret;
    int  num;
} scent_t;

/* actually 335 currently but too lazy to handwrite 7 more */
#define MAX_SCS 329

#define MAX_SIGS 63

static const scent_t ALLSCS[]=
{
    {"read", {U, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"write", {U, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"open", {CHAR_PTR, INT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"close", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"stat", {CHAR_PTR, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"fstat", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"lstat", {CHAR_PTR, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"poll", {STRUCT, U, LONG, OFF, OFF, OFF}, RETVAL, 3},
    {"lseek", {U, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"mmap", {PTR, U_L, U_L, U_L, U_L, U_L}, PTR, 6},
    {"mprotect", {U_L, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"munmap", {U_L, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"brk", {PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"rt_sigaction", {INT, STRUCT, STRUCT, U, OFF, OFF}, RETVAL, 4},
    {"rt_sigprocmask", {INT, STRUCT, STRUCT, U, OFF, OFF}, RETVAL, 4},
    {"rt_sigreturn", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"ioctl", {U, U, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"pread64", {U_L, CHAR_PTR, U, U, OFF, OFF}, RETVAL, 4},
    {"pwrite64", {U_L, CHAR_PTR, U, U, OFF, OFF}, RETVAL, 4},
    {"readv", {U_L, STRUCT, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"writev", {U_L, STRUCT, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"access", {CHAR_PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"pipe", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"select", {INT, PTR, OFF, OFF, OFF, OFF}, RETVAL, 5},
    {"sched_yield", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"mremap", {U_L, U_L, U_L, U_L, U_L, OFF}, RETVAL, 5},
    {"msync", {U_L, U, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"mincore", {U_L, U, CHAR_PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"madvise", {U_L, U, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"shmget", {U, U, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"shmat", {INT, CHAR_PTR, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"shmctl", {INT, INT, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"dup", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"dup2", {U, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"pause", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"nanosleep", {STRUCT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getitimer", {INT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"alarm", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"setitimer", {INT, STRUCT, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"getpid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"sendfile", {INT, INT, U, PTR, OFF, OFF}, RETVAL, 4},
    {"socket", {INT, INT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"connect", {INT, STRUCT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"accept", {INT, STRUCT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"sendto", {INT, PTR, U, U, STRUCT, INT}, RETVAL, 6},
    {"recvfrom", {INT, PTR, U, U, STRUCT, INT}, RETVAL, 6},
    {"sendmsg", {INT, STRUCT, U, OFF, OFF, OFF}, RETVAL, 3},
    {"recvmsg", {INT, STRUCT, U, OFF, OFF, OFF}, RETVAL, 3},
    {"shutdown", {INT, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"bind", {INT, STRUCT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"listen", {INT, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getsockname", {INT, STRUCT, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"getpeername", {INT, STRUCT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"socketpair", {INT, INT, INT, PTR, OFF, OFF}, RETVAL, 4},
    {"setsockopt", {INT, INT, INT, CHAR_PTR, INT, OFF}, RETVAL, 5},
    {"getsockopt", {INT, INT, INT, CHAR_PTR, PTR, OFF}, RETVAL, 5},
    {"clone", {U_L, U_L, PTR, PTR, OFF, OFF}, RETVAL, 4},
    {"fork", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"vfork", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"execve", {CHAR_PTR, CHAR_PTRPTR, CHAR_PTRPTR, OFF, OFF, OFF}, RETVAL, 3},
    {"exit", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"wait4", {U, PTR, INT, STRUCT, OFF, OFF}, RETVAL, 4},
    {"kill", {U, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"uname", {STRUCT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"semget", {U, INT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"semop", {INT, STRUCT, U, OFF, OFF, OFF}, RETVAL, 3},
    {"semctl", {INT, INT, INT, PTR, OFF, OFF}, RETVAL, 4},
    {"shmdt", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"msgget", {U, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"msgsnd", {INT, STRUCT, U, INT, OFF, OFF}, RETVAL, 4},
    {"msgrcv", {INT, STRUCT, U, LONG, INT, OFF}, RETVAL, 5},
    {"msgctl", {INT, INT, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"fcntl", {U, U, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"flock", {U, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"fsync", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"fdatasync", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"truncate", {CHAR_PTR, LONG, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"ftruncate", {U, U_L, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getdents", {U, STRUCT, U, OFF, OFF, OFF}, RETVAL, 3},
    {"getcwd", {CHAR_PTR, U_L, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"chdir", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"fchdir", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"rename", {CHAR_PTR, CHAR_PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"mkdir", {CHAR_PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"rmdir", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"creat", {CHAR_PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"link", {CHAR_PTR, CHAR_PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"unlink", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"symlink", {CHAR_PTR, CHAR_PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"readlink", {CHAR_PTR, CHAR_PTR, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"chmod", {CHAR_PTR, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"fchmod", {U, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"chown", {CHAR_PTR, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"fchown", {U, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"lchown", {CHAR_PTR, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"umask", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"gettimeofday", {STRUCT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getrlimit", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getrusage", {INT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"sysinfo", {STRUCT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"times", {STRUCT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"ptrace", {LONG, LONG, U, U, OFF, OFF}, RETVAL, 4},
    {"getuid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"syslog", {INT, CHAR_PTR, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"getgid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"setuid", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"setgid", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"geteuid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"getegid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"setpgid", {U, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getppid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"getpgrp", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"setsid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"setreuid", {U,  U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"setregid", {U, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getgroups", {INT, PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"setgroups", {INT, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"setresuid", {PTR, PTR, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"getresuid", {PTR, PTR, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"setresgid", {U, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"getresgid", {PTR, PTR, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"getpgid", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"setfsuid", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"setfsgid", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"getsid", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"capget", {STRUCT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"capset", {STRUCT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"rt_sigpending", {U, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"rt_sigtimedwait", {PTR, PTR, STRUCT, U, OFF, OFF}, RETVAL, 4},
    {"rt_sigqueueinfo", {U, INT, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"rt_sigsuspend", {PTR, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"sigaltstack", {PTR, PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"utime", {CHAR_PTR, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"mknod", {CHAR_PTR, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"uselib", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"personality", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"ustat", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"statfs", {CHAR_PTR, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"fstatfs", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"sysfs", {INT, U_L, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"getpriority", {INT, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"setpriority", {INT, INT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"sched_setparam", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"sched_getparam", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"sched_setscheduler", {INT, INT, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"sched_getscheduler", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"sched_get_priority_max", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"sched_get_priority_min", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"sched_rr_get_interval", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"mlock", {U_L, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"munlock", {U_L, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"mlockall", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"munlockall", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"vhangup", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"modify_ldt", {INT, PTR, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"pivot_root", {CHAR_PTR, CHAR_PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"_sysctl", {STRUCT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"prctl", {INT, U_L, U_L, U_L, OFF, U}, RETVAL, 5},
    {"arch_prctl", {STRUCT, INT, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"adjtimex", {STRUCT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"setrlimit", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"chroot", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"sync", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"acct", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"settimeofday", {STRUCT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"mount", {CHAR_PTR, CHAR_PTR, CHAR_PTR, U, PTR, OFF}, RETVAL, 5},
    {"umount2", {CHAR_PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"swapon", {CHAR_PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"swapoff", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"reboot", {INT, INT, U, PTR, OFF, OFF}, RETVAL, 4},
    {"sethostname", {CHAR_PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"setdomainname", {CHAR_PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"iopl", {U_L, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"ioperm", {U, U, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"create_module", {U_L, U_L, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"init_module", {PTR, U_L, CHAR_PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"delete_module", {CHAR_PTR, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"get_kernel_syms", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"query_module", {U, U, U, U, U, OFF}, RETVAL, 5},
    {"quotactl", {U, CHAR_PTR, U, PTR, OFF, OFF}, RETVAL, 4},
    {"nfsservctl", {U, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"getpmsg", {U, U, U, U, U, OFF}, RETVAL, 5},
    {"putpmsg", {U, U, U, U, U, OFF}, RETVAL, 5},
    {"afs_syscall", {U, U, U, U, U, OFF}, RETVAL, 5},
    {"tuxcall", {U, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"security", {U, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"gettid", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"readahead", {INT, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"setxattr", {CHAR_PTR, CHAR_PTR, PTR, U, INT, OFF}, RETVAL, 5},
    {"lsetxattr", {CHAR_PTR, CHAR_PTR, PTR, U, INT, OFF}, RETVAL, 5},
    {"fsetxattr", {INT, CHAR_PTR, PTR, U, INT, OFF}, RETVAL, 5},
    {"getxattr", {CHAR_PTR, CHAR_PTR, PTR, U, OFF, OFF}, RETVAL, 4},
    {"lgetxattr", {CHAR_PTR, CHAR_PTR, PTR, U, OFF, OFF}, RETVAL, 4},
    {"fgetxattr", {INT, CHAR_PTR, PTR, U, OFF, OFF}, RETVAL, 4},
    {"listxattr", {CHAR_PTR, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"llistxattr", {CHAR_PTR, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"flistxattr", {INT, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"removexattr", {CHAR_PTR, CHAR_PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"lremovexattr", {CHAR_PTR, CHAR_PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"fremovexattr", {INT, CHAR_PTR, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"tkill", {U, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"time", {PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"futex", {PTR, INT, U, STRUCT, PTR, U}, RETVAL, 6},
    {"sched_setaffinity", {U, U, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"sched_getaffinity", {U, U, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"set_thread_area", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"io_setup", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"io_destroy", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"io_getevents", {PTR, LONG, LONG, STRUCT, OFF, OFF}, RETVAL, 4},
    {"io_submit", {PTR, LONG, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"io_cancel", {PTR, STRUCT, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"get_thread_area", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"lookup_dcookie", {U, LONG, LONG, OFF, OFF, OFF}, RETVAL, 3},
    {"epoll_create", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"epoll_ctl_old", {U, U, U, U, OFF, OFF}, RETVAL, 4},
    {"epoll_wait_old", {U, U, U, U, OFF, OFF}, RETVAL, 4},
    {"remap_file_pages", {U_L, U_L, U_L, U_L, U_L, OFF}, RETVAL, 5},
    {"getdents64", {U, STRUCT, U, OFF, OFF, OFF}, RETVAL, 3},
    {"set_tid_address", {PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"restart_syscall", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"semtimedop", {INT, STRUCT, U, STRUCT, OFF, OFF}, RETVAL, 4},
    {"fadvise64", {INT, U, U, INT, OFF, OFF}, RETVAL, 4},
    {"timer_create", {U, STRUCT, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"timer_settime", {U, INT, STRUCT, STRUCT, OFF, OFF}, RETVAL, 4},
    {"timer_gettime", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"timer_getoverrun", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"timer_delete", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"clock_settime", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"clock_gettime", {U,  STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"clock_getres", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"clock_nanosleep", {U, INT, STRUCT, STRUCT, OFF, OFF}, RETVAL, 4},
    {"exit_group", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"epoll_wait", {INT, STRUCT, INT, INT, OFF, OFF}, RETVAL, 4},
    {"epoll_ctl", {INT, INT, INT, STRUCT, OFF, OFF}, RETVAL, 4},
    {"tgkill", {U, U, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"utimes", {CHAR_PTR, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"vserver", {U, U, U, U, U, OFF}, RETVAL, 5},
    {"mbind", {U, U, U_L, PTR, U_L, U}, RETVAL, 6},
    {"set_mempolicy", {PTR, U_L, U_L, OFF, OFF, OFF}, RETVAL, 3},
    {"get_mempolicy", {PTR, PTR, U_L, U_L, U_L, OFF}, RETVAL, 5},
    {"mq_open", {CHAR_PTR, INT, U, STRUCT, OFF, OFF}, RETVAL, 4},
    {"mq_unlink", {CHAR_PTR, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"mq_timedsend", {U, CHAR_PTR, U, U, STRUCT, OFF}, RETVAL, 5},
    {"mq_timedreceive", {U, CHAR_PTR, U, U, STRUCT, OFF}, RETVAL, 5},
    {"mq_notify", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"mq_getsetattr", {U, STRUCT, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"kexec_load", {U_L, U_L, STRUCT, U_L, OFF, OFF}, RETVAL, 4},
    {"waitid", {INT, U, STRUCT, INT, STRUCT, OFF}, RETVAL, 5},
    {"add_key", {CHAR_PTR, CHAR_PTR, CHAR_PTR, U, OFF, OFF}, RETVAL, 4},
    {"request_key", {CHAR_PTR, CHAR_PTR, CHAR_PTR, U, OFF, OFF}, RETVAL, 4},
    {"keyctl", {INT, U_L, U_L, U_L, U_L, OFF}, RETVAL, 5},
    {"ioprio_set", {INT, INT, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"ioprio_get", {INT, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"inotify_init", {OFF, OFF, OFF, OFF, OFF, OFF}, RETVAL, 0},
    {"inotify_add_watch", {INT, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"inotify_rm_watch", {INT, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"migrate_pages", {U, U_L, PTR, PTR, OFF, OFF}, RETVAL, 4},
    {"openat", {INT, CHAR_PTR, INT, INT, OFF, OFF}, RETVAL, 4},
    {"mkdirat", {INT, CHAR_PTR, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"mknodat", {INT, CHAR_PTR, INT, U, OFF, OFF}, RETVAL, 4},
    {"fchownat", {INT, CHAR_PTR, U, U, INT, OFF}, RETVAL, 5},
    {"futimesat", {INT, CHAR_PTR, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"newfstatat", {INT, CHAR_PTR, STRUCT, INT, OFF, OFF}, RETVAL, 4},
    {"unlinkat", {INT, CHAR_PTR, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"renameat", {INT, CHAR_PTR, INT, CHAR_PTR, OFF, OFF}, RETVAL, 4},
    {"linkat", {INT, CHAR_PTR, INT, CHAR_PTR, INT, OFF}, RETVAL, 5},
    {"symlinkat", {CHAR_PTR, INT, CHAR_PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"readlinkat", {INT, CHAR_PTR, CHAR_PTR, INT, OFF, OFF}, RETVAL, 4},
    {"fchmodat", {INT, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"faccessat", {INT, CHAR_PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"pselect6", {INT, PTR, PTR, PTR, STRUCT, PTR}, RETVAL, 6},
    {"ppoll", {STRUCT, U, STRUCT, PTR, U, OFF}, RETVAL, 5},
    {"unshare", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"set_robust_list", {STRUCT, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"get_robust_list", {INT, STRUCT, PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"splice", {INT, PTR, INT, PTR, U, U}, RETVAL, 6},
    {"tee", {INT, INT, U, U, OFF, OFF}, RETVAL, 4},
    {"sync_file_range", {LONG, U, U, LONG, OFF, OFF}, RETVAL, 4},
    {"vmsplice", {INT, STRUCT, U_L, U, OFF, OFF}, RETVAL, 4},
    {"move_pages", {U, U_L, PTR, PTR, PTR, INT}, RETVAL, 6},
    {"utimensat", {INT, CHAR_PTR, STRUCT, INT, OFF, OFF}, RETVAL, 4},
    {"epoll_pwait", {INT, STRUCT, INT, INT, PTR, U}, RETVAL, 6},
    {"signalfd", {INT, PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"timerfd_create", {INT, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"eventfd", {U, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"fallocate", {LONG, LONG, U, U, OFF, OFF}, RETVAL, 4},
    {"timerfd_settime", {INT, INT, STRUCT, STRUCT, OFF, OFF}, RETVAL, 4},
    {"timerfd_gettime", {INT, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"accept4", {INT, STRUCT, PTR, INT, OFF, OFF}, RETVAL, 4},
    {"signalfd4", {INT, STRUCT, INT, INT, OFF, OFF}, RETVAL, 4},
    {"eventfd2", {U, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"epoll_create1", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"dup3", {U, U, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"pipe2", {PTR, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"inotify_init1", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"preadv", {U_L, STRUCT, U_L, U_L, U_L, OFF}, RETVAL, 5},
    {"pwritev", {U_L, STRUCT, U_L, U_L, U_L, OFF}, RETVAL, 5},
    {"rt_tgsigqueueinfo", {U, U, INT, PTR, OFF, OFF}, RETVAL, 4},
    {"perf_event_open", {STRUCT, U, INT, INT, U_L, OFF}, RETVAL, 5},
    {"recvmmsg", {INT, STRUCT, U, U, STRUCT, OFF}, RETVAL, 5},
    {"fanotify_init", {U, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"fanotify_mark", {LONG, LONG, U, LONG, LONG, OFF}, RETVAL, 5},
    {"prlimit64", {U, U, STRUCT, STRUCT, OFF, OFF}, RETVAL, 4},
    {"name_to_handle_at", {INT, CHAR_PTR, STRUCT, PTR, INT, OFF}, RETVAL, 5},
    {"open_by_handle_at", {INT, CHAR_PTR, STRUCT, PTR, INT, OFF}, RETVAL, 5},
    {"clock_adjtime", {U, STRUCT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"syncfs", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"sendmmsg", {INT, STRUCT, U, U, OFF, OFF}, RETVAL, 4},
    {"setns", {INT, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"getcpu", {PTR, PTR, STRUCT, OFF, OFF, OFF}, RETVAL, 3},
    {"process_vm_readv", {U, STRUCT, U_L, STRUCT, U_L, U_L}, RETVAL, 6},
    {"process_vm_writev", {U, STRUCT, U_L, STRUCT, U_L, U_L}, RETVAL, 6},
    {"kcmp", {U, U, INT, U_L, U_L, OFF}, RETVAL, 5},
    {"finit_module", {INT, CHAR_PTR, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"sched_setattr", {U, STRUCT, U, OFF, OFF, OFF}, RETVAL, 3},
    {"sched_getattr", {U, STRUCT, U, U, OFF, OFF}, RETVAL, 4},
    {"renameat2", {INT, CHAR_PTR, INT, CHAR_PTR, U, OFF}, RETVAL, 5},
    {"seccomp", {U, U, CHAR_PTR, OFF, OFF, OFF}, RETVAL, 3},
    {"getrandom", {CHAR_PTR, U, U, OFF, OFF, OFF}, RETVAL, 3},
    {"memfd_create", {CHAR_PTR, U, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"kexec_file_load", {INT, INT, U_L, CHAR_PTR, U_L, OFF}, RETVAL, 5},
    {"bpf", {INT, PTR, U, OFF, OFF, OFF}, RETVAL, 3},
    {"execveat", {INT, CHAR_PTR, PTR, PTR, INT, OFF}, RETVAL, 5},
    {"userfaultfd", {INT, OFF, OFF, OFF, OFF, OFF}, RETVAL, 1},
    {"membarrier", {INT, INT, OFF, OFF, OFF, OFF}, RETVAL, 2},
    {"mlock2", {U_L, U, INT, OFF, OFF, OFF}, RETVAL, 3},
    {"copy_file_range", {INT, PTR, INT, PTR, U, U}, RETVAL, 6},
    {"preadv2", {U_L, STRUCT, U_L, U_L, U_L, INT}, RETVAL, 6},
    {"pwritev2", {U_L, STRUCT, U_L, U_L, U_L, INT}, RETVAL, 6},
};

static char const * const ALLSIGS[] =
{
  "Undefined",
  "SIGHUP",
  "SIGINT",
  "SIGQUIT",
  "SIGILL",
  "SIGTRAP",
  "SIGABRT",
  "SIGBUS",
  "SIGFPE",
  "SIGKILL",
  "SIGUSR1",
  "SIGSEGV",
  "SIGUSR2",
  "SIGPIPE",
  "SIGALRM",
  "SIGTERM",
  "SIGSTKFLT",
  "SIGCHLD",
  "SIGCONT",
  "SIGSTOP",
  "SIGTSTP",
  "SIGTTIN",
  "SIGTTOU",
  "SIGURG",
  "SIGXCPU",
  "SIGXFSZ",
  "SIGVTALRM",
  "SIGPROF",
  "SIGWINCH",
  "SIGIO",
  "SIGPWR",
  "SIGSYS",
  "SIGRTMIN",
  "SIGRTMIN+1",
  "SIGRTMIN+2",
  "SIGRTMIN+3",
  "SIGRTMIN+4",
  "SIGRTMIN+5",
  "SIGRTMIN+6",
  "SIGRTMIN+7",
  "SIGRTMIN+8",
  "SIGRTMIN+9",
  "SIGRTMIN+10",
  "SIGRTMIN+11",
  "SIGRTMIN+12",
  "SIGRTMIN+13",
  "SIGRTMIN+14",
  "SIGRTMIN+15",
  "SIGRTMAX-14",
  "SIGRTMAX-13",
  "SIGRTMAX-12",
  "SIGRTMAX-11",
  "SIGRTMAX-10",
  "SIGRTMAX-9",
  "SIGRTMAX-8",
  "SIGRTMAX-7",
  "SIGRTMAX-6",
  "SIGRTMAX-5",
  "SIGRTMAX-4",
  "SIGRTMAX-3",
  "SIGRTMAX-2",
  "SIGRTMAX-1",
  "SIGRTMAX",
};

#endif
